spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: graphgl-test

server:
  port: 8080

logging:
  path: ./target/log/
  pattern.file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5level [%8.-8mdc{requestGUID}] %-40.40logger{39}:%6.-6line : %msg%n%xEx"
  level:
    root: INFO
    ru.cinimex: TRACE
    graphql: TRACE
    graphql.execution.ExecutionStrategy: INFO

graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true
