# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).

### Get schema (no need read authority)
http://127.0.0.1:8080/graphql?query={__schema {types {name, fields {name}}}}
Authorization: Basic user-noread user

### Get all books via GET (read authority needed) - OK
http://127.0.0.1:8080/graphql?query={books{name, description, carModels {name, description}}}
Authorization: Basic user-read user

### Get all books via GET (read authority needed) - ERROR
http://127.0.0.1:8080/graphql?query={books{name, description, carModels {name, description}}}
Authorization: Basic user-noread user

### Get all books via POST
POST http://127.0.0.1:8080/graphql
Content-Type: application/json
Authorization: Basic admin admin

{"query": authors}

###